modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Scouter456/Cobblemon_Outbreaks/issues" #optional
[[mods]] #mandatory
modId="cobblemonoutbreaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cobblemon Outbreaks" #mandatory
logoFile="cobblemonoutbreaks_logo.png" #optional
credits="" #optional
authors="Scouter" #optional

description='''
This mod adds outbreaks similar to those in Legends Arceus!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cobblemonoutbreaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblemonoutbreaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblemonoutbreaks]]
    modId="cobblemon"
    mandatory=true
    versionRange="[1.3.1+1.19.2,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.cobblemonoutbreaks]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[3,)"
    ordering="BEFORE"
    side="BOTH"
# Change this if you require a certain version of KotlinForForge
