modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Scouter456/Cobblemon_Lucky_Blocks/issues" #optional
[[mods]] #mandatory
modId="cobblelucky" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cobblemon Lucky Blocks" #mandatory
logoFile="cobblemon_lucky_block_logo.png" #optional
credits="" #optional
authors="Scouter" #optional

description='''
This mod adds two lucky blocks, that can give random pokemon or items!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cobblelucky]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblelucky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblelucky]]
    modId="cobblemon"
    mandatory=true
    versionRange="[1.3.1+1.19.2,)"
    ordering="BEFORE"
    side="BOTH"